import type { Metadata } from 'next'
import { Koulen } from 'next/font/google'

import '@/app/globals.css'

const koulen = Koulen({ weight: '400', subsets: ['khmer'] })

export const metadata: Metadata = {
  title: 'SportsHub',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={koulen.className}>{children}</body>
    </html>
  )
}
