import type { Metadata } from 'next'
import { Koulen } from 'next/font/google'

import './globals.css'
import { AuthProvider } from '@/providers/auth-provider'
import { Toaster } from 'react-hot-toast'

const koulen = Koulen({ weight: '400', subsets: ['khmer'] })

export const metadata: Metadata = {
  title: 'SportsHub',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={koulen.className}>
        <Toaster position="top-right" reverseOrder={false} />

        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  )
}
