import type { Metadata } from 'next'
import { Koulen } from 'next/font/google'
import NavBar from './components/navBar'
import './globals.css'

const koulen = Koulen({ weight: '400', subsets: ['khmer'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={koulen.className}>
        <NavBar></NavBar>

        {children}
      </body>
    </html>
  )
}
